package entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class Report {

    private final LocalDateTime generatedAt;                 
    private final FilterCriteria criteria;                   
    private final List<InternshipOpportunity> opportunities; 
    private final String summary;                           
    private final CareerCenterStaff generatedBy;            

    public Report(CareerCenterStaff generatedBy, FilterCriteria criteria,
                  List<InternshipOpportunity> opportunities) {
        this.generatedAt = LocalDateTime.now();
        this.generatedBy = generatedBy;
        this.criteria = Objects.requireNonNull(criteria);
        this.opportunities = (opportunities != null) ? opportunities : new ArrayList<>();
        this.summary = generateSummary();

    }

    /** 
     * @return String
     */
    private String generateSummary() {
        String staffName = (generatedBy != null) ? generatedBy.getName() : "Unknown Staff";
        return String.format("Report generated by %s on %s with %d opportunities.",
                staffName, generatedAt, opportunities.size());
    }

    /**
     * returns the timestamp when this withdrawal request was reviewed.
     *
     * @return the review date and time, or null if not yet reviewed
     */
    public LocalDateTime getGeneratedAt() { return generatedAt; }
    public FilterCriteria getCriteria() { return criteria; }
    public List<InternshipOpportunity> getOpportunities() { return opportunities; }
    public String getSummary() { return summary; }
    public CareerCenterStaff getGeneratedBy() { return generatedBy; }

    /** 
     * @return String
     */
    @Override
    public String toString() {
        return String.format("Report[by=%s, generatedAt=%s, opportunities=%d]",
                generatedBy != null ? generatedBy.getName() : "Unknown",
                generatedAt,
                opportunities.size());
    }
}

