package entity;

import java.util.*;
import enumerations.*;

/**
 * Represents a report generated by Career Center Staff based on selected filter criteria.
 * A report contains a list of internship opportunities that match the given filters.
 */
public class Report {

    // === Attributes (from UML) ===
    private Date generatedAt;                                    // Timestamp of report creation
    private FilterCriteria criteria;                             // Filter used to generate this report
    private List<InternshipOpportunity> opportunities;           // Opportunities that matched the filter
    private String summary;                                      // Summary of the report
    private CareerCenterStaff generatedBy;                       // The staff who created this report

    // === Constructor ===
    public Report(CareerCenterStaff generatedBy, FilterCriteria criteria,
                  List<InternshipOpportunity> opportunities) {
        this.generatedAt = new Date();
        this.generatedBy = generatedBy;
        this.criteria = criteria;
        this.opportunities = opportunities != null ? opportunities : new ArrayList<>();
        this.summary = generateSummary();

        // link report back to staff (if bi-directional association is needed)
        if (generatedBy != null) {
            generatedBy.addReport(this);
        }
    }

    // === Summary generator ===
    private String generateSummary() {
        String staffName = (generatedBy != null) ? generatedBy.getName() : "Unknown Staff";
        return String.format("Report generated by %s on %s with %d opportunities.",
                staffName, generatedAt, opportunities.size());
    }

    // === Getters ===
    public Date getGeneratedAt() { return generatedAt; }
    public FilterCriteria getCriteria() { return criteria; }
    public List<InternshipOpportunity> getOpportunities() { return opportunities; }
    public String getSummary() { return summary; }
    public CareerCenterStaff getGeneratedBy() { return generatedBy; }

    // === Optional ===
    @Override
    public String toString() {
        return String.format("Report[by=%s, generatedAt=%s, opportunities=%d]",
                generatedBy != null ? generatedBy.getName() : "Unknown",
                generatedAt,
                opportunities != null ? opportunities.size() : 0);
    }
}
