package entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** A generated snapshot of opportunities for given criteria. */
public class Report {

    // === Attributes (from UML) ===
    private final LocalDateTime generatedAt;                 // Timestamp of report creation
    private final FilterCriteria criteria;                   // Filter used to generate this report
    private final List<InternshipOpportunity> opportunities; // Opportunities that matched the filter
    private final String summary;                            // Summary of the report
    private final CareerCenterStaff generatedBy;             // The staff who created this report

    // === Constructor ===
    public Report(CareerCenterStaff generatedBy, FilterCriteria criteria,
                  List<InternshipOpportunity> opportunities) {
        this.generatedAt = LocalDateTime.now();
        this.generatedBy = generatedBy;
        this.criteria = Objects.requireNonNull(criteria);
        this.opportunities = (opportunities != null) ? opportunities : new ArrayList<>();
        this.summary = generateSummary();

        // If you later add a List<Report> in CareerCenterStaff, you can link back here.
        // if (generatedBy != null) generatedBy.addReport(this);
    }

    // === Summary generator ===
    private String generateSummary() {
        String staffName = (generatedBy != null) ? generatedBy.getName() : "Unknown Staff";
        return String.format("Report generated by %s on %s with %d opportunities.",
                staffName, generatedAt, opportunities.size());
    }

    // === Getters ===
    public LocalDateTime getGeneratedAt() { return generatedAt; }
    public FilterCriteria getCriteria() { return criteria; }
    public List<InternshipOpportunity> getOpportunities() { return opportunities; }
    public String getSummary() { return summary; }
    public CareerCenterStaff getGeneratedBy() { return generatedBy; }

    // === Optional ===
    @Override
    public String toString() {
        return String.format("Report[by=%s, generatedAt=%s, opportunities=%d]",
                generatedBy != null ? generatedBy.getName() : "Unknown",
                generatedAt,
                opportunities.size());
    }
}

